node {

   stage('Clone Repository') {
        // Get some code from a GitHub repository
        git 'https://github.com/Aaqib041/Metro-Smart-Card-System.git'

   }

   stage('Publish') {
        withDockerRegistry([ credentialsId: "a6944791-4326-4bd5-bd89-6a8836381124", url: "" ]) {
          sh 'docker push akeeb/mscs:${env.BUILD_NUMBER}'
        }
    }
}
